import React, { createContext, useContext, useState } from 'react';

const translations = {
  en: {
    // Navbar
    navHome: 'Home',
    navDocs: 'Docs',
    navPremium: 'Pricing',
    navStatus: 'Status',
    navSupport: 'Support',
    navMore: 'More',
    navDashboard: 'Dashboard',
    navLogin: 'Log In',
    navLogout: 'Log Out',
    moreApiEndpoints: 'API Endpoints',
    moreSdkIntegrations: 'SDK Integrations',
    moreSecurityHardening: 'Security Hardening',
    moreTokenGate: 'Token Validation Gate',
    moreSystemStatus: 'System Status',

    // Hero
    heroBadgeText: 'Habit Auth v1.4 • Cloud & Hardware Security',
    heroTitlePrefix: 'The ultimate licensing solution for',
    heroSubtitle: 'Enterprise-grade authentication, hardware ID locking, and zero-trust anti-tamper security for modern desktop & cloud applications.',
    heroBtnStart: 'Start for free →',
    heroBtnDocs: 'View Documentation',
    heroCheckZeroFee: 'Zero Setup Fee',
    heroCheckSigned: 'Ed25519 Signed',
    heroCheckHwid: 'Instant HWID Lock',
    heroActiveLicenses: 'Active Protected Licenses',
    heroUptime: 'Handshake SLA Uptime',
    heroZeroReplay: 'Zero-Replay Nonce Security',
    heroGlobalNodes: 'Edge Verification Latency',

    // Dashboard Mockup Preview
    mockupActiveLicenses: 'Active Licenses',
    mockupBoundHwid: 'Bound HWIDs',
    mockupBlockedAttacks: 'Blocked Attacks',
    mockupAuditHealth: 'Audit Health',
    mockupTabLogs: 'Audit Logs',
    mockupTabLicenses: 'Licenses',
    mockupStatusLive: 'WAL Engine Live',

    // Metrics Bar
    metricHwid: 'SHA-256 HWID',
    metricHwidDesc: 'Hardware Multi-Sensor Lock',
    metricLatency: '< 12ms Latency',
    metricLatencyDesc: 'Sub-Second SQLite WAL Engine',
    metricSigned: 'Signed Replies',
    metricSignedDesc: 'Ed25519 & HMAC-SHA256',
    metricWebhooks: 'Instant Webhooks',
    metricWebhooksDesc: 'Telegram Bots & Discord Roles',

    // 6 Pillars
    pillarsBadge: 'Comprehensive Protection Stack',
    pillarsTitle: 'Why Developers Choose Habit Auth',
    pillarsSubtitle: 'Manage applications, licenses, users, tokens, sessions, files, variables, logs, and enterprise controls from one unified panel.',
    pillar1Title: '1. Signed Cryptographic Responses',
    pillar1Desc: 'Every API reply is digitally signed with an Ed25519 private key and validated client-side. Attackers using Fiddler or Charles Proxy cannot forge a "success" reply.',
    pillar1Tag: 'Immune to HTTP Proxy Spoofing',
    pillar2Title: '2. SHA-256 Multi-Sensor HWID Binding',
    pillar2Desc: 'Irreversibly binds user licenses to motherboard UUID, CPU architecture, and drive serial numbers. Prevents credential sharing and multi-device abuse.',
    pillar2Tag: 'Zero License Sharing',
    pillar3Title: '3. Dynamic Pre-Login Token Validation',
    pillar3Desc: 'Require clients to present an encrypted application token file before the user can access the login routine. Blocks automated scrapers and decompiled binaries.',
    pillar3Tag: 'Pre-Handshake Gatekeeping',
    pillar4Title: '4. 1-Click IP & HWID Blacklisting',
    pillar4Desc: 'Detect and immediately terminate malicious actors. Client IP and hardware IDs are logged automatically, allowing you to ban a device or network segment with a single click.',
    pillar4Tag: 'Instant Global Blacklisting',
    pillar5Title: '5. Telegram Bots & Discord Webhook Roles',
    pillar5Desc: 'Configure granular event routing. Send user registrations, logins, bans, license generations, and security infractions to designated Discord channels or Telegram chats.',
    pillar5Tag: 'Real-Time Incident Notifications',
    pillar6Title: '6. Smart 30-Day DB Retention & Backup',
    pillar6Desc: 'Automated maintenance routines purge expired audit logs while keeping disk usage minimal with 1-click JSON/CSV backup downloads before deletion.',
    pillar6Tag: 'Zero Database Bloat',

    // SDK Showcase
    sdkBadge: 'Premade Examples - SDKs',
    sdkTitle: 'Drop-in Integration in Minutes',
    sdkSubtitle: 'Habit Auth supports modern v1.4 signed routines across multiple languages. Select your language below to inspect initialization code:',
    sdkDownloadTemplate: 'Download Full SDK Template',

    // FAQ
    faqBadge: 'Knowledge Base',
    faqTitle: 'Frequently Asked Questions',
    faqQ1: 'How does Habit Auth prevent proxy tools like Fiddler or Charles?',
    faqA1: 'Every response sent from our API is cryptographically signed using an Ed25519 private key. The client SDK verifies this signature against our public key. If an attacker modifies or fakes the response payload, signature verification fails and the app terminates immediately.',
    faqQ2: 'What hardware identifiers are used for the HWID lock?',
    faqA2: 'Our multi-sensor fingerprinting engine computes a SHA-256 hash using the motherboard UUID, primary CPU processor ID, and drive volume serial numbers. Even if a user changes their network or reinstalls their operating system, the hardware lock remains valid.',
    faqQ3: 'Can I migrate my existing users and licenses from KeyAuth?',
    faqA3: 'Yes! Habit Auth provides a 1-click JSON/CSV importer compatible with KeyAuth schemas. You can import all your applications, users, passwords, HWIDs, and active license keys in under two minutes with zero downtime.',
    faqQ4: 'Does Habit Auth work with offline applications?',
    faqA4: 'Habit Auth offers signed offline lease tokens with custom expiration policies. Applications can cache a cryptographically signed lease token and run without an active internet connection until the lease duration expires.',

    // CTA Banner
    ctaBadge: 'Instant Setup in < 5 Minutes',
    ctaTitle: 'Ready to secure your software?',
    ctaSubtitle: "Power your application's licensing and user authentication with Habit Auth today.",
    ctaGetStarted: 'Start for Free →',
    ctaGetSupport: 'Join Discord Community',

    // Pricing
    pricingBadge: 'Transparent & Flexible Pricing',
    pricingTitle: 'Choose the Perfect Plan for Your Software',
    pricingSubtitle: 'From solo indie developers to enterprise distribution, scale securely with Habit Auth.',
    pricingMonthly: 'Monthly Billing',
    pricingYearly: 'Yearly Billing',
    pricingSave20: 'SAVE 20%',

    // Footer
    footerDesc: 'Enterprise-grade authentication, license validation, and hardware-locked security infrastructure designed for software creators.',
    footerPlatform: 'Platform',
    footerResources: 'Resources',
    footerLegal: 'Legal',
    footerRights: 'All rights reserved. Designed for elite developers.',
    footerStatusLive: 'All Systems Operational',

    // Dashboard
    dashScope: 'Current App Scope',
    dashPlatform: 'PLATFORM',
    dashManagement: 'MANAGEMENT',
    dashDevTools: 'DEVELOPER TOOLS',
    dashAdministration: 'ADMINISTRATION',
    dashOverview: 'Overview',
    dashApps: 'Applications',
    dashUsers: 'Users',
    dashLicenses: 'Licenses',
    dashDevices: 'Devices (HWID)',
    dashBanned: 'Banned HWIDs',
    dashWebhooks: 'Webhooks',
    dashTeams: 'Teams',
    dashSdks: 'SDKs & Code',
    dashDocs: 'API Docs',
    dashSecurity: 'Security & Tokens',
    dashAudit: 'Audit Logs',
    dashLiveSessions: 'Live Sessions',
    dashSupport: 'Support',
    dashAdmin: 'Admin System',
    dashStatus: 'System Status',
    dashTotalLicenses: 'Total Active Licenses',
    dashActiveUsers: 'Active Users',
    dashLockedHwid: 'Bound HWIDs',
    dashBlockedAttacks: 'Blocked Attacks',
    dashCreateApp: 'Create Application',
    dashGenLicense: 'Generate License',
    dashSearch: 'Search applications, users...',
    dashLogout: 'Log Out',
    dashUpgrade: 'Upgrade Plan',
    dashBackToLanding: 'Visit Website',
    dashActions: 'Quick Actions',
    dashCurrentPlan: 'Current Plan',
    dashYourApps: 'Your Applications',
    dashManageAppsSubtitle: 'Click an application to manage users, licenses, and security',

    // Theme & Lang
    themeDark: 'Dark Mode',
    themeLight: 'Light Mode',
    switchLang: 'Language',
  },

  bn: {
    // Navbar
    navHome: 'হোম',
    navDocs: 'ডকুমেন্টেশন',
    navPremium: 'প্রাইসিং',
    navStatus: 'স্ট্যাটাস',
    navSupport: 'সাপোর্ট',
    navMore: 'আরও',
    navDashboard: 'ড্যাশবোর্ড',
    navLogin: 'লগ ইন',
    navLogout: 'লগ আউট',
    moreApiEndpoints: 'এপিআই এন্ডপয়েন্ট',
    moreSdkIntegrations: 'এসডিকে ইন্টিগ্রেশন',
    moreSecurityHardening: 'সিকিউরিটি হার্ডেনিং',
    moreTokenGate: 'টোকেন ভ্যালিডেশন গেট',
    moreSystemStatus: 'সিস্টেম স্ট্যাটাস',

    // Hero
    heroBadgeText: 'হ্যাবিট অথ v১.৪ • ক্লাউড ও হার্ডওয়্যার সিকিউরিটি',
    heroTitlePrefix: 'সর্বাধুনিক লাইসেন্সিং প্ল্যাটফর্ম',
    heroSubtitle: 'আধুনিক ডেস্কটপ ও ক্লাউড অ্যাপ্লিকেশনের জন্য এন্টারপ্রাইজ-গ্রেড অথেন্টিকেশন, হার্ডওয়্যার আইডি লকিং এবং জিরো-ট্রাস্ট অ্যান্টি-ট্যাম্পার সিকিউরিটি।',
    heroBtnStart: 'বিনামূল্যে শুরু করুন →',
    heroBtnDocs: 'ডকুমেন্টেশন দেখুন',
    heroCheckZeroFee: 'জিরো সেটআপ ফি',
    heroCheckSigned: 'Ed25519 সাইনড',
    heroCheckHwid: 'তাত্ক্ষণিক HWID লক',
    heroActiveLicenses: 'সক্রিয় সুরক্ষিত লাইসেন্স',
    heroUptime: 'হ্যান্ডশেক এসএলএ আপটাইম',
    heroZeroReplay: 'জিরো-রিপ্লে ননস সুরক্ষা',
    heroGlobalNodes: 'এজ ভেরিফিকেশন লেটেন্সি',

    // Dashboard Mockup Preview
    mockupActiveLicenses: 'সক্রিয় লাইসেন্স',
    mockupBoundHwid: 'বাউন্ড HWID',
    mockupBlockedAttacks: 'প্রতিহত আক্রমণ',
    mockupAuditHealth: 'অডিট হেলথ',
    mockupTabLogs: 'অডিট লগ',
    mockupTabLicenses: 'লাইসেন্সসমূহ',
    mockupStatusLive: 'WAL ইঞ্জিন সক্রিয়',

    // Metrics Bar
    metricHwid: 'SHA-256 HWID',
    metricHwidDesc: 'মাল্টি-সেন্সর হার্ডওয়্যার লক',
    metricLatency: '< ১২ms লেটেন্সি',
    metricLatencyDesc: 'সাব-সেকেন্ড SQLite WAL ইঞ্জিন',
    metricSigned: 'ডিজিটাল সাইনড রিপ্লাই',
    metricSignedDesc: 'Ed25519 এবং HMAC-SHA256',
    metricWebhooks: 'তাত্ক্ষণিক ওয়েবহুক',
    metricWebhooksDesc: 'টেলিগ্রাম বট ও ডিসকর্ড রোল',

    // 6 Pillars
    pillarsBadge: 'কম্প্রিহেনসিভ সিকিউরিটি স্ট্যাক',
    pillarsTitle: 'ডেভেলপাররা কেন হ্যাবিট অথ বেছে নেয়',
    pillarsSubtitle: 'একটি একক ড্যাশবোর্ড থেকে অ্যাপ্লিকেশান, লাইসেন্স, ব্যবহারকারী, টোকেন, সেশন এবং রিসেলার কন্ট্রোল পরিচালনা করুন।',
    pillar1Title: '১. সাইনড ক্রিপ্টোগ্রাফিক রেসপন্স',
    pillar1Desc: 'প্রতিটি এপিআই রেসপন্স Ed25519 প্রাইভেট কি দিয়ে ডিজিটালি সাইন করা হয়। ফিডলার বা প্রক্সি টুল দিয়ে কেউ ভুয়া সাকসেস তৈরি করতে পারে না।',
    pillar1Tag: 'এইচটিটিপি প্রক্সি স্পুফিং প্রতিরোধী',
    pillar2Title: '২. SHA-256 মাল্টি-সেন্সর HWID বাইন্ডিং',
    pillar2Desc: 'ইউজারের লাইসেন্স সরাসরি মাদারবোর্ড UUID, CPU এবং ড্রাইভ সিরিয়ালে লক করে দেয়। লাইসেন্স শেয়ারিং সম্পূর্ণ বন্ধ করে।',
    pillar2Tag: 'জিরো লাইসেন্স শেয়ারিং',
    pillar3Title: '৩. ডাইনামিক প্রি-লগইন টোকেন ভ্যালিডেশন',
    pillar3Desc: 'লগইন রুটিনে প্রবেশের আগেই এনক্রিপ্টেড অ্যাপ্লিকেশন টোকেন ফাইল যাচাই করে। অটোমেটেড স্ক্র্যাপার ও ডিকম্পাইল্ড বাইনারি ব্লক করে।',
    pillar3Tag: 'প্রি-হ্যান্ডশেক গেটকিপিং',
    pillar4Title: '৪. ১-ক্লিক আইপি ও HWID ব্ল্যাকলিস্টিং',
    pillar4Desc: 'সন্দেহভাজন বা ক্ষতিকর আক্রমণকারীদের চিহ্নিত করে তাৎক্ষণিকভাবে ১-ক্লিকেই তাদের আইপি বা হার্ডওয়্যার নিষিদ্ধ করুন।',
    pillar4Tag: 'তাত্ক্ষণিক গ্লোবাল ব্ল্যাকলিস্ট',
    pillar5Title: '৫. টেলিগ্রাম বট ও ডিসকর্ড ওয়েবহুক রোল',
    pillar5Desc: 'রিয়েল-টাইমে ইউজার রেজিস্ট্রেশন, লগইন, ব্যান এবং লাইসেন্স অ্যাক্টিভেশনের নোটিফিকেশন ডিসকর্ড চ্যানেল বা টেলিগ্রাম বোটে পাঠান।',
    pillar5Tag: 'রিয়েল-টাইম ঘটনা নোটিফিকেশন',
    pillar6Title: '৬. স্মার্ট ৩০ দিনের অডিট ব্যাকআপ ও রিটেনশন',
    pillar6Desc: 'অটোমেটেড রুটিন ডাটাবেজ অপ্টিমাইজ রাখে এবং মেয়াদোত্তীর্ণ লগ স্বয়ংক্রিয়ভাবে ব্যাকআপ ডাউনলোড সুবিধা সহ পরিষ্কার করে।',
    pillar6Tag: 'জিরো ডাটাবেজ ব্লট',

    // SDK Showcase
    sdkBadge: 'তৈরি করা এসডিকে উদাহরণ',
    sdkTitle: 'কয়েক মিনিটেই ইন্টিগ্রেশন সম্পন্ন',
    sdkSubtitle: 'হ্যাবিট অথ বিভিন্ন প্রোগ্রামিং ভাষার জন্য আধুনিক v১.৪ সাইনড লাইব্রেরি সাপোর্ট করে। কোড দেখতে নিচে ভাষা নির্বাচন করুন:',
    sdkDownloadTemplate: 'সম্পূর্ণ এসডিকে টেমপ্লেট ডাউনলোড করুন',

    // FAQ
    faqBadge: 'সাধারণ প্রশ্নোত্তর',
    faqTitle: 'বহুল জিজ্ঞাসিত প্রশ্নসমূহ',
    faqQ1: 'হ্যাবিট অথ কীভাবে ফিডলার বা চার্লস প্রক্সি আক্রমণ প্রতিহত করে?',
    faqA1: 'প্রতিটি এপিআই রিপ্লাই Ed25519 প্রাইভেট কি দিয়ে ডিজিটালি সাইন করা থাকে। ক্লায়েন্ট এসডিকে পাবলিক কি দ্বারা এটি যাচাই করে। কোনো আক্রমণকারী রেসপন্স পরিবর্তন করলে সিগনেচার ফেইল করে এবং অ্যাপ বন্ধ হয়ে যায়।',
    faqQ2: 'HWID লকের জন্য কোন হার্ডওয়্যার সনাক্তকারী ব্যবহার করা হয়?',
    faqA2: 'আমাদের মাল্টি-সেন্সর ইঞ্জিন মাদারবোর্ড UUID, প্রধান CPU প্রসেসর আইডি এবং ড্রাইভ সিরিয়াল নম্বর একত্রিত করে SHA-256 হ্যাশ তৈরি করে। ওএস রিইন্সটল করলেও এই লক অক্ষত থাকে।',
    faqQ3: 'আমি কি KeyAuth থেকে আমার বর্তমান ইউজার ও লাইসেন্স মাইগ্রেট করতে পারব?',
    faqA3: 'হ্যাঁ! হ্যাবিট অথে ১-ক্লিকেই KeyAuth এর সাথে সামঞ্জস্যপূর্ণ JSON/CSV ফাইল ইমপোর্ট করা যায়। কোনো ডাউনটাইম ছাড়াই দুই মিনিটে সব ডাটা চলে আসবে।',
    faqQ4: 'হ্যাবিট অথ কি অফলাইন অ্যাপ্লিকেশনে কাজ করে?',
    faqA4: 'হ্যাবিট অথে রয়েছে সাইনড অফলাইন লিজ টোকেন সুবিধা। অ্যাপ্লিকেশন একটি ক্রিপ্টোগ্রাফিক লিজ ক্যাশ করে ইন্টারনেট ছাড়াই নির্ধারিত মেয়াদ পর্যন্ত চলতে পারে।',

    // CTA Banner
    ctaBadge: '৫ মিনিটের মধ্যে ইনস্ট্যান্ট সেটআপ',
    ctaTitle: 'আপনার সফটওয়্যার সুরক্ষিত করতে প্রস্তুত?',
    ctaSubtitle: 'আজই হ্যাবিট অথের মাধ্যমে আপনার অ্যাপ্লিকেশনের লাইসেন্সিং ও অথেন্টিকেশন শুরু করুন।',
    ctaGetStarted: 'বিনামূল্যে শুরু করুন →',
    ctaGetSupport: 'ডিসকর্ড কমিউনিটিতে যুক্ত হন',

    // Pricing
    pricingBadge: 'স্বচ্ছ প্রাইসিং প্ল্যান',
    pricingTitle: 'আপনার সফটওয়্যারের জন্য উপযুক্ত প্ল্যান নির্বাচন করুন',
    pricingSubtitle: 'ইন্ডি ডেভেলপার থেকে শুরু করে এন্টারপ্রাইজ—সব স্কেলেই সুরক্ষিত থাকুক আপনার প্রজেক্ট।',
    pricingMonthly: 'মাসিক বিলিং',
    pricingYearly: 'বার্ষিক বিলিং',
    pricingSave20: '২০% সেভ',

    // Footer
    footerDesc: 'ডেভেলপারদের জন্য মিলিটারি-গ্রেড অথেন্টিকেশন, লাইসেন্স যাচাইকরণ এবং অ্যান্টি-রিভার্স ইঞ্জিনিয়ারিং সিকিউরিটি প্ল্যাটফর্ম।',
    footerPlatform: 'প্ল্যাটফর্ম',
    footerResources: 'রিসোর্সসমূহ',
    footerLegal: 'আইনি তথ্য',
    footerRights: 'সর্বস্বত্ব সংরক্ষিত। ডেভেলপারদের জন্য নির্মিত।',
    footerStatusLive: 'সকল সিস্টেম সক্রিয় ও সচল',

    // Dashboard
    dashScope: 'বর্তমান অ্যাপ স্কোপ',
    dashPlatform: 'প্ল্যাটফর্ম',
    dashManagement: 'ম্যানেজমেন্ট',
    dashDevTools: 'ডেভেলপার টুলস',
    dashAdministration: 'অ্যাডমিনিস্ট্রেশন',
    dashOverview: 'ওভারভিউ',
    dashApps: 'অ্যাপ্লিকেশানসমূহ',
    dashUsers: 'ব্যবহারকারীগণ',
    dashLicenses: 'লাইসেন্সসমূহ',
    dashDevices: 'ডিভাইসসমূহ (HWID)',
    dashBanned: 'নিষিদ্ধ HWID',
    dashWebhooks: 'ওয়েবহুক',
    dashTeams: 'টিম',
    dashSdks: 'এসডিকে ও কোড',
    dashDocs: 'এপিআই ডক্স',
    dashSecurity: 'সিকিউরিটি ও টোকেন',
    dashAudit: 'অডিট লগ',
    dashLiveSessions: 'লাইভ সেশন',
    dashSupport: 'সাপোর্ট',
    dashAdmin: 'অ্যাডমিন সিস্টেম',
    dashStatus: 'সিস্টেম স্ট্যাটাস',
    dashTotalLicenses: 'মোট সক্রিয় লাইসেন্স',
    dashActiveUsers: 'সক্রিয় ব্যবহারকারী',
    dashLockedHwid: 'বাউন্ড HWID',
    dashBlockedAttacks: 'প্রতিহত আক্রমণ',
    dashCreateApp: 'নতুন অ্যাপ তৈরি',
    dashGenLicense: 'লাইসেন্স তৈরি',
    dashSearch: 'অ্যাপ, ইউজার অনুসন্ধান...',
    dashLogout: 'লগ আউট',
    dashUpgrade: 'প্ল্যান আপগ্রেড',
    dashBackToLanding: 'ওয়েবসাইটে যান',
    dashActions: 'কুইক অ্যাকশন',
    dashCurrentPlan: 'বর্তমান প্ল্যান',
    dashYourApps: 'আপনার অ্যাপ্লিকেশনসমূহ',
    dashManageAppsSubtitle: 'ইউজার, লাইসেন্স এবং সিকিউরিটি পরিচালনা করতে অ্যাপ্লিকেশনে ক্লিক করুন',

    // Theme & Lang
    themeDark: 'ডার্ক মোড',
    themeLight: 'লাইট মোড',
    switchLang: 'ভাষা পরিবর্তন',
  },

  es: {
    navHome: 'Inicio',
    navDocs: 'Documentación',
    navPremium: 'Precios',
    navStatus: 'Estado',
    navSupport: 'Soporte',
    navMore: 'Más',
    navDashboard: 'Panel',
    navLogin: 'Iniciar Sesión',
    navLogout: 'Cerrar Sesión',
    moreApiEndpoints: 'Puntos Finales API',
    moreSdkIntegrations: 'Integraciones SDK',
    moreSecurityHardening: 'Seguridad Reforzada',
    moreTokenGate: 'Validación de Token',
    moreSystemStatus: 'Estado del Sistema',
    heroBadgeText: 'Habit Auth v1.4 • Seguridad en la Nube y Hardware',
    heroTitlePrefix: 'La solución definitiva de licencias para',
    heroSubtitle: 'Autenticación de nivel empresarial, bloqueo por ID de hardware y seguridad antimanipulación de confianza cero.',
    heroBtnStart: 'Comenzar gratis →',
    heroBtnDocs: 'Ver Documentación',
    heroCheckZeroFee: 'Sin Costo de Instalación',
    heroCheckSigned: 'Firmado con Ed25519',
    heroCheckHwid: 'Bloqueo HWID Inmediato',
    mockupActiveLicenses: 'Licencias Activas',
    mockupBoundHwid: 'HWIDs Bloqueados',
    mockupBlockedAttacks: 'Ataques Bloqueados',
    mockupAuditHealth: 'Salud de Auditoría',
    mockupTabLogs: 'Registros de Auditoría',
    mockupTabLicenses: 'Licencias',
    mockupStatusLive: 'Motor WAL Activo',
    metricHwid: 'SHA-256 HWID',
    metricHwidDesc: 'Bloqueo Multi-Sensor de Hardware',
    metricLatency: '< 12ms Latencia',
    metricLatencyDesc: 'Motor SQLite WAL Ultrarrápido',
    metricSigned: 'Respuestas Firmadas',
    metricSignedDesc: 'Ed25519 y HMAC-SHA256',
    metricWebhooks: 'Webhooks Instantáneos',
    metricWebhooksDesc: 'Bots de Telegram y Roles de Discord',
    pillarsBadge: 'Pila Integral de Protección',
    pillarsTitle: 'Por qué los Desarrolladores Eligen Habit Auth',
    pillarsSubtitle: 'Administre aplicaciones, licencias, usuarios, tokens y controles desde un panel unificado.',
    sdkBadge: 'Ejemplos Preconstruidos - SDKs',
    sdkTitle: 'Integración en Cuestión de Minutos',
    sdkSubtitle: 'Habit Auth admite rutinas firmadas v1.4 en múltiples lenguajes:',
    sdkDownloadTemplate: 'Descargar Plantilla SDK Completa',
    faqBadge: 'Base de Conocimientos',
    faqTitle: 'Preguntas Frecuentes',
    ctaBadge: 'Configuración en < 5 Minutos',
    ctaTitle: '¿Listo para proteger su software?',
    ctaSubtitle: 'Potencie el licenciamiento y autenticación de su aplicación con Habit Auth.',
    ctaGetStarted: 'Comenzar Gratis →',
    ctaGetSupport: 'Comunidad de Discord',
    pricingBadge: 'Precios Transparentes',
    pricingTitle: 'Elija el Plan Perfecto para su Software',
    pricingSubtitle: 'Escale de forma segura con Habit Auth.',
    pricingMonthly: 'Facturación Mensual',
    pricingYearly: 'Facturación Anual',
    pricingSave20: 'AHORRE 20%',
    footerDesc: 'Infraestructura de autenticación y licencias diseñada para creadores de software.',
    footerPlatform: 'Plataforma',
    footerResources: 'Recursos',
    footerLegal: 'Legal',
    footerRights: 'Todos los derechos reservados. Diseñado para desarrolladores de élite.',
    footerStatusLive: 'Todos los Sistemas Operativos',
    dashScope: 'Ámbito de Aplicación Actual',
    dashPlatform: 'PLATAFORMA',
    dashManagement: 'GESTIÓN',
    dashDevTools: 'HERRAMIENTAS DE DESARROLLO',
    dashAdministration: 'ADMINISTRACIÓN',
    dashOverview: 'Resumen',
    dashApps: 'Aplicaciones',
    dashUsers: 'Usuarios',
    dashLicenses: 'Licencias',
    dashDevices: 'Dispositivos (HWID)',
    dashBanned: 'HWIDs Bloqueados',
    dashWebhooks: 'Webhooks',
    dashTeams: 'Equipos',
    dashSdks: 'SDKs y Código',
    dashDocs: 'Documentación API',
    dashSecurity: 'Seguridad y Tokens',
    dashAudit: 'Registros de Auditoría',
    dashLiveSessions: 'Sesiones en Vivo',
    dashSupport: 'Soporte',
    dashAdmin: 'Sistema de Administración',
    dashStatus: 'Estado del Sistema',
    dashTotalLicenses: 'Total de Licencias Activas',
    dashActiveUsers: 'Usuarios Activos',
    dashLockedHwid: 'HWIDs Vinculados',
    dashBlockedAttacks: 'Ataques Bloqueados',
    dashCreateApp: 'Crear Aplicación',
    dashGenLicense: 'Generar Licencia',
    dashSearch: 'Buscar aplicaciones, usuarios...',
    dashLogout: 'Cerrar Sesión',
    dashUpgrade: 'Mejorar Plan',
    dashBackToLanding: 'Visitar Sitio Web',
    dashActions: 'Acciones Rápidas',
    themeDark: 'Modo Oscuro',
    themeLight: 'Modo Claro',
    switchLang: 'Idioma',
  },

  de: {
    navHome: 'Startseite',
    navDocs: 'Dokumentation',
    navPremium: 'Preise',
    navStatus: 'Status',
    navSupport: 'Support',
    navMore: 'Mehr',
    navDashboard: 'Dashboard',
    navLogin: 'Anmelden',
    navLogout: 'Abmelden',
    moreApiEndpoints: 'API-Endpunkte',
    moreSdkIntegrations: 'SDK-Integrationen',
    moreSecurityHardening: 'Sicherheitshärtung',
    moreTokenGate: 'Token-Validierung',
    moreSystemStatus: 'Systemstatus',
    heroBadgeText: 'Habit Auth v1.4 • Cloud- & Hardwaresicherheit',
    heroTitlePrefix: 'Die ultimative Lizenzierungslösung für',
    heroSubtitle: 'Authentifizierung auf Unternehmensniveau, Hardware-ID-Sperre und Zero-Trust-Sicherheit.',
    heroBtnStart: 'Kostenlos starten →',
    heroBtnDocs: 'Dokumentation ansehen',
    heroCheckZeroFee: 'Keine Einrichtungsgebühr',
    heroCheckSigned: 'Ed25519 Signiert',
    heroCheckHwid: 'Sofortige HWID-Sperre',
    mockupActiveLicenses: 'Aktive Lizenzen',
    mockupBoundHwid: 'Gebundene HWIDs',
    mockupBlockedAttacks: 'Blockierte Angriffe',
    mockupAuditHealth: 'Audit-Status',
    mockupTabLogs: 'Audit-Protokolle',
    mockupTabLicenses: 'Lizenzen',
    mockupStatusLive: 'WAL-Engine Aktiv',
    metricHwid: 'SHA-256 HWID',
    metricHwidDesc: 'Multi-Sensor-Hardwaresperre',
    metricLatency: '< 12ms Latenz',
    metricLatencyDesc: 'Sub-Sekunden SQLite WAL-Engine',
    metricSigned: 'Signierte Antworten',
    metricSignedDesc: 'Ed25519 & HMAC-SHA256',
    metricWebhooks: 'Sofortige Webhooks',
    metricWebhooksDesc: 'Telegram-Bots & Discord-Rollen',
    pillarsBadge: 'Umfassender Schutz-Stack',
    pillarsTitle: 'Warum Entwickler Habit Auth wählen',
    pillarsSubtitle: 'Verwalten Sie Anwendungen, Lizenzen, Benutzer und Tokens über ein zentrales Dashboard.',
    sdkBadge: 'Vorgefertigte SDK-Beispiele',
    sdkTitle: 'Drop-in-Integration in Minuten',
    sdkSubtitle: 'Habit Auth unterstützt moderne v1.4-Routinen in mehreren Programmiersprachen:',
    sdkDownloadTemplate: 'Vollständiges SDK herunterladen',
    faqBadge: 'Wissensdatenbank',
    faqTitle: 'Häufig gestellte Fragen',
    ctaBadge: 'Einrichtung in < 5 Minuten',
    ctaTitle: 'Bereit, Ihre Software zu sichern?',
    ctaSubtitle: 'Starten Sie noch heute mit Habit Auth.',
    ctaGetStarted: 'Kostenlos starten →',
    ctaGetSupport: 'Discord-Community beitreten',
    pricingBadge: 'Transparente Preise',
    pricingTitle: 'Wählen Sie den perfekten Plan',
    pricingSubtitle: 'Skalieren Sie sicher mit Habit Auth.',
    pricingMonthly: 'Monatliche Abrechnung',
    pricingYearly: 'Jährliche Abrechnung',
    pricingSave20: '20% SPAREN',
    footerDesc: 'Sicherheitsinfrastruktur für Softwareentwickler.',
    footerPlatform: 'Plattform',
    footerResources: 'Ressourcen',
    footerLegal: 'Rechtliches',
    footerRights: 'Alle Rechte vorbehalten.',
    footerStatusLive: 'Alle Systeme betriebsbereit',
    dashScope: 'Aktueller App-Bereich',
    dashPlatform: 'PLATTFORM',
    dashManagement: 'VERWALTUNG',
    dashDevTools: 'ENTWICKLER-TOOLS',
    dashAdministration: 'ADMINISTRATION',
    dashOverview: 'Übersicht',
    dashApps: 'Anwendungen',
    dashUsers: 'Benutzer',
    dashLicenses: 'Lizenzen',
    dashDevices: 'Geräte (HWID)',
    dashBanned: 'Gesperrte HWIDs',
    dashWebhooks: 'Webhooks',
    dashTeams: 'Teams',
    dashSdks: 'SDKs & Code',
    dashDocs: 'API-Dokumentation',
    dashSecurity: 'Sicherheit & Tokens',
    dashAudit: 'Audit-Protokolle',
    dashLiveSessions: 'Live-Sitzungen',
    dashSupport: 'Support',
    dashAdmin: 'Admin-System',
    dashStatus: 'Systemstatus',
    dashTotalLicenses: 'Aktive Lizenzen insgesamt',
    dashActiveUsers: 'Aktive Benutzer',
    dashLockedHwid: 'Gebundene HWIDs',
    dashBlockedAttacks: 'Blockierte Angriffe',
    dashCreateApp: 'Anwendung erstellen',
    dashGenLicense: 'Lizenz generieren',
    dashSearch: 'Suchen...',
    dashLogout: 'Abmelden',
    dashUpgrade: 'Plan upgraden',
    dashBackToLanding: 'Zur Website',
    dashActions: 'Schnellaktionen',
    themeDark: 'Dunkelmodus',
    themeLight: 'Hellmodus',
    switchLang: 'Sprache',
  },

  fr: {
    navHome: 'Accueil',
    navDocs: 'Documentation',
    navPremium: 'Tarifs',
    navStatus: 'Statut',
    navSupport: 'Support',
    navMore: 'Plus',
    navDashboard: 'Tableau de bord',
    navLogin: 'Connexion',
    navLogout: 'Déconnexion',
    moreApiEndpoints: 'Points de terminaison API',
    moreSdkIntegrations: 'Intégrations SDK',
    moreSecurityHardening: 'Renforcement Sécurité',
    moreTokenGate: 'Validation de Jeton',
    moreSystemStatus: 'Statut du Système',
    heroBadgeText: 'Habit Auth v1.4 • Sécurité Cloud & Matérielle',
    heroTitlePrefix: 'La solution ultime de licences pour',
    heroSubtitle: 'Authentification de niveau entreprise, verrouillage HWID et sécurité anti-altération zéro-confiance.',
    heroBtnStart: 'Démarrer gratuitement →',
    heroBtnDocs: 'Voir la Documentation',
    heroCheckZeroFee: 'Aucun Frais de Configuration',
    heroCheckSigned: 'Signé Ed25519',
    heroCheckHwid: 'Verrouillage HWID Instantané',
    mockupActiveLicenses: 'Licences Actives',
    mockupBoundHwid: 'HWIDs Liés',
    mockupBlockedAttacks: 'Attaques Bloquées',
    mockupAuditHealth: 'Santé Audit',
    mockupTabLogs: 'Journaux d\'Audit',
    mockupTabLicenses: 'Licences',
    mockupStatusLive: 'Moteur WAL Actif',
    metricHwid: 'SHA-256 HWID',
    metricHwidDesc: 'Verrou Matériel Multi-Capteurs',
    metricLatency: '< 12ms Latence',
    metricLatencyDesc: 'Moteur SQLite WAL Ultrarapide',
    metricSigned: 'Réponses Signées',
    metricSignedDesc: 'Ed25519 & HMAC-SHA256',
    metricWebhooks: 'Webhooks Instantanés',
    metricWebhooksDesc: 'Bots Telegram & Rôles Discord',
    pillarsBadge: 'Pile de Protection Complète',
    pillarsTitle: 'Pourquoi les Développeurs Choisissent Habit Auth',
    pillarsSubtitle: 'Gérez vos applications, licences, utilisateurs et contrôles depuis un panneau unifié.',
    sdkBadge: 'Exemples SDK Prêts à l\'Emploi',
    sdkTitle: 'Intégration en Quelques Minutes',
    sdkSubtitle: 'Habit Auth prend en charge les routines signées v1.4 dans plusieurs langages :',
    sdkDownloadTemplate: 'Télécharger le Template SDK',
    faqBadge: 'Base de Connaissances',
    faqTitle: 'Foire Aux Questions',
    ctaBadge: 'Configuration en < 5 Minutes',
    ctaTitle: 'Prêt à sécuriser votre logiciel ?',
    ctaSubtitle: 'Sécurisez vos licences avec Habit Auth dès aujourd\'hui.',
    ctaGetStarted: 'Démarrer Gratuitement →',
    ctaGetSupport: 'Rejoindre la Communauté Discord',
    pricingBadge: 'Tarifs Transparents',
    pricingTitle: 'Choisissez le Plan Parfait pour Votre Logiciel',
    pricingSubtitle: 'Évoluez en toute sécurité avec Habit Auth.',
    pricingMonthly: 'Facturation Mensuelle',
    pricingYearly: 'Facturation Annuelle',
    pricingSave20: 'ÉCONOMISEZ 20%',
    footerDesc: 'Infrastructure d\'authentification et de licences conçue pour les développeurs.',
    footerPlatform: 'Plateforme',
    footerResources: 'Ressources',
    footerLegal: 'Légal',
    footerRights: 'Tous droits réservés.',
    footerStatusLive: 'Tous les Systèmes Opérationnels',
    dashScope: 'Portée de l\'App Actuelle',
    dashPlatform: 'PLATEFORME',
    dashManagement: 'GESTION',
    dashDevTools: 'OUTILS DÉVELOPPEUR',
    dashAdministration: 'ADMINISTRATION',
    dashOverview: 'Vue d\'ensemble',
    dashApps: 'Applications',
    dashUsers: 'Utilisateurs',
    dashLicenses: 'Licences',
    dashDevices: 'Appareils (HWID)',
    dashBanned: 'HWIDs Bannis',
    dashWebhooks: 'Webhooks',
    dashTeams: 'Équipes',
    dashSdks: 'SDKs & Code',
    dashDocs: 'Documentation API',
    dashSecurity: 'Sécurité & Jetons',
    dashAudit: 'Journaux d\'Audit',
    dashLiveSessions: 'Sessions en Direct',
    dashSupport: 'Support',
    dashAdmin: 'Système d\'Administration',
    dashStatus: 'Statut du Système',
    dashTotalLicenses: 'Total Licences Actives',
    dashActiveUsers: 'Utilisateurs Actifs',
    dashLockedHwid: 'HWIDs Liés',
    dashBlockedAttacks: 'Attaques Bloquées',
    dashCreateApp: 'Créer une Application',
    dashGenLicense: 'Générer une Licence',
    dashSearch: 'Rechercher...',
    dashLogout: 'Déconnexion',
    dashUpgrade: 'Mettre à Niveau',
    dashBackToLanding: 'Visiter le Site Web',
    dashActions: 'Actions Rapides',
    themeDark: 'Mode Sombre',
    themeLight: 'Mode Clair',
    switchLang: 'Langue',
  },

  ru: {
    navHome: 'Главная',
    navDocs: 'Документация',
    navPremium: 'Тарифы',
    navStatus: 'Статус',
    navSupport: 'Поддержка',
    navMore: 'Еще',
    navDashboard: 'Панель',
    navLogin: 'Войти',
    navLogout: 'Выйти',
    moreApiEndpoints: 'API Эндпоинты',
    moreSdkIntegrations: 'SDK Интеграции',
    moreSecurityHardening: 'Усиление Безопасности',
    moreTokenGate: 'Шлюз Валидации Токенов',
    moreSystemStatus: 'Статус Системы',
    heroBadgeText: 'Habit Auth v1.4 • Облачная и Аппаратная Защита',
    heroTitlePrefix: 'Лучшее решение для лицензирования для',
    heroSubtitle: 'Аутентификация корпоративного уровня, блокировка по HWID и защита от взлома нулевого доверия.',
    heroBtnStart: 'Начать бесплатно →',
    heroBtnDocs: 'Документация',
    heroCheckZeroFee: 'Без Платы за Настройку',
    heroCheckSigned: 'Ed25519 Подпись',
    heroCheckHwid: 'Мгновенная Блокировка HWID',
    mockupActiveLicenses: 'Активные Лицензии',
    mockupBoundHwid: 'Привязанные HWID',
    mockupBlockedAttacks: 'Отраженные Атаки',
    mockupAuditHealth: 'Здоровье Системы',
    mockupTabLogs: 'Аудит Логи',
    mockupTabLicenses: 'Лицензии',
    mockupStatusLive: 'WAL Движок Активен',
    metricHwid: 'SHA-256 HWID',
    metricHwidDesc: 'Мульти-сенсорная Аппаратная Блокировка',
    metricLatency: '< 12мс Задержка',
    metricLatencyDesc: 'Сверхбыстрый SQLite WAL Движок',
    metricSigned: 'Подписанные Ответы',
    metricSignedDesc: 'Ed25519 и HMAC-SHA256',
    metricWebhooks: 'Мгновенные Вебхуки',
    metricWebhooksDesc: 'Telegram-боты и Discord-роли',
    pillarsBadge: 'Комплексный Стек Защиты',
    pillarsTitle: 'Почему Разработчики Выбирают Habit Auth',
    pillarsSubtitle: 'Управляйте приложениями, лицензиями, пользователями и токенами из единой панели.',
    sdkBadge: 'Готовые SDK Примеры',
    sdkTitle: 'Интеграция за Несколько Минут',
    sdkSubtitle: 'Habit Auth поддерживает современные v1.4 протоколы на различных языках программирования:',
    sdkDownloadTemplate: 'Скачать Шаблон SDK',
    faqBadge: 'База Знаний',
    faqTitle: 'Часто Задаваемые Вопросы',
    ctaBadge: 'Настройка за < 5 Минут',
    ctaTitle: 'Готовы защитить свое ПО?',
    ctaSubtitle: 'Начните лицензирование с Habit Auth уже сегодня.',
    ctaGetStarted: 'Начать Бесплатно →',
    ctaGetSupport: 'Discord Сообщество',
    pricingBadge: 'Прозрачные Цены',
    pricingTitle: 'Выберите Идеальный Тариф',
    pricingSubtitle: 'Масштабируйтесь безопасно вместе с Habit Auth.',
    pricingMonthly: 'Ежемесячная Оплата',
    pricingYearly: 'Ежегодная Оплата',
    pricingSave20: 'СКИДКА 20%',
    footerDesc: 'Инфраструктура аутентификации и лицензирования для создателей программного обеспечения.',
    footerPlatform: 'Платформа',
    footerResources: 'Ресурсы',
    footerLegal: 'Правовая информация',
    footerRights: 'Все права защищены.',
    footerStatusLive: 'Все Системы Работают Штатно',
    dashScope: 'Текущее Приложение',
    dashPlatform: 'ПЛАТФОРМА',
    dashManagement: 'УПРАВЛЕНИЕ',
    dashDevTools: 'ИНСТРУМЕНТЫ РАЗРАБОТЧИКА',
    dashAdministration: 'АДМИНИСТРИРОВАНИЕ',
    dashOverview: 'Обзор',
    dashApps: 'Приложения',
    dashUsers: 'Пользователи',
    dashLicenses: 'Лицензии',
    dashDevices: 'Устройства (HWID)',
    dashBanned: 'Заблокированные HWID',
    dashWebhooks: 'Вебхуки',
    dashTeams: 'Команды',
    dashSdks: 'SDK и Код',
    dashDocs: 'API Документация',
    dashSecurity: 'Безопасность и Токены',
    dashAudit: 'Журналы Аудита',
    dashLiveSessions: 'Активные Сессии',
    dashSupport: 'Поддержка',
    dashAdmin: 'Панель Администратора',
    dashStatus: 'Статус Системы',
    dashTotalLicenses: 'Всего Активных Лицензий',
    dashActiveUsers: 'Активные Пользователи',
    dashLockedHwid: 'Привязанные HWID',
    dashBlockedAttacks: 'Отраженные Атаки',
    dashCreateApp: 'Создать Приложение',
    dashGenLicense: 'Создать Лицензию',
    dashSearch: 'Поиск...',
    dashLogout: 'Выйти',
    dashUpgrade: 'Улучшить Тариф',
    dashBackToLanding: 'На Главную',
    dashActions: 'Быстрые Действия',
    themeDark: 'Темная Тема',
    themeLight: 'Светлая Тема',
    switchLang: 'Язык',
  },

  zh: {
    navHome: '首页',
    navDocs: '文档',
    navPremium: '定价方案',
    navStatus: '运行状态',
    navSupport: '技术支持',
    navMore: '更多',
    navDashboard: '控制台',
    navLogin: '登录',
    navLogout: '退出登录',
    moreApiEndpoints: 'API 接口列表',
    moreSdkIntegrations: 'SDK 代码集成',
    moreSecurityHardening: '安全加固指引',
    moreTokenGate: '动态令牌校验网关',
    moreSystemStatus: '系统运行状态',
    heroBadgeText: 'Habit Auth v1.4 • 云端与硬件级安全',
    heroTitlePrefix: '专为开发者打造的终极软件授权方案：',
    heroSubtitle: '企业级身份验证、硬件特征码（HWID）深度绑定与零信任防篡改安全防护。',
    heroBtnStart: '免费开启 →',
    heroBtnDocs: '查阅开发文档',
    heroCheckZeroFee: '零设置费',
    heroCheckSigned: 'Ed25519 数字签名',
    heroCheckHwid: '实时 HWID 锁定',
    mockupActiveLicenses: '活跃授权',
    mockupBoundHwid: '绑定硬件数',
    mockupBlockedAttacks: '拦截攻击数',
    mockupAuditHealth: '审计状态',
    mockupTabLogs: '安全审计日志',
    mockupTabLicenses: '授权码管理',
    mockupStatusLive: 'WAL 引擎运行中',
    metricHwid: 'SHA-256 HWID',
    metricHwidDesc: '多传感器硬件特征深度锁定',
    metricLatency: '< 12ms 极速响应',
    metricLatencyDesc: '亚毫秒级 SQLite WAL 引擎',
    metricSigned: '防篡改数字签名',
    metricSignedDesc: 'Ed25519 与 HMAC-SHA256',
    metricWebhooks: '即时 Webhook',
    metricWebhooksDesc: 'Telegram 机器人与 Discord 角色',
    pillarsBadge: '全栈式安全保护体系',
    pillarsTitle: '为何众多开发者选择 Habit Auth',
    pillarsSubtitle: '在统一的可视化面板中轻松管理软件应用、授权码、设备指纹及分销商权限。',
    sdkBadge: '现成示例 - 多语言 SDK',
    sdkTitle: '数分钟内轻松接入',
    sdkSubtitle: 'Habit Auth 支持现代 v1.4 安全协议，请在下方选择您的编程语言：',
    sdkDownloadTemplate: '下载完整 SDK 模板',
    faqBadge: '知识库与解答',
    faqTitle: '常见问题解答',
    ctaBadge: '可在 5 分钟内完成部署',
    ctaTitle: '准备好保护您的软件资产了吗？',
    ctaSubtitle: '立即使用 Habit Auth 为您的软件应用提供坚不可摧的安全授权。',
    ctaGetStarted: '免费开始使用 →',
    ctaGetSupport: '加入 Discord 开发者社区',
    pricingBadge: '清晰透明的价格方案',
    pricingTitle: '为您的软件挑选最合适的授权方案',
    pricingSubtitle: '从独立开发者到企业级分发，安全随心扩展。',
    pricingMonthly: '按月订阅',
    pricingYearly: '按年订阅',
    pricingSave20: '立省 20%',
    footerDesc: '专为专业开发者打造的军工级授权验证与反逆向安全基础设施。',
    footerPlatform: '平台',
    footerResources: '开发资源',
    footerLegal: '法律条款',
    footerRights: '版权所有。专为开发者打造。',
    footerStatusLive: '所有系统正常运行',
    dashScope: '当前选定应用',
    dashPlatform: '平台中心',
    dashManagement: '业务管理',
    dashDevTools: '开发者工具',
    dashAdministration: '系统管理',
    dashOverview: '总览看板',
    dashApps: '应用程序管理',
    dashUsers: '注册用户列表',
    dashLicenses: '授权卡密管理',
    dashDevices: '设备指纹 (HWID)',
    dashBanned: '黑名单硬件 (HWID)',
    dashWebhooks: '事件 Webhook',
    dashTeams: '团队协作',
    dashSdks: 'SDK 与示例代码',
    dashDocs: 'API 接口文档',
    dashSecurity: '安全配置与令牌',
    dashAudit: '安全审计日志',
    dashLiveSessions: '实时在线会话',
    dashSupport: '工单技术支持',
    dashAdmin: '管理员系统配置',
    dashStatus: '系统运行状态',
    dashTotalLicenses: '有效授权总数',
    dashActiveUsers: '活跃用户数',
    dashLockedHwid: '已绑定硬件数',
    dashBlockedAttacks: '拦截攻击总数',
    dashCreateApp: '创建新应用',
    dashGenLicense: '批量生成授权码',
    dashSearch: '搜索应用、用户或授权码...',
    dashLogout: '退出登录',
    dashUpgrade: '升级方案',
    dashBackToLanding: '返回首页',
    dashActions: '快捷操作',
    themeDark: '深色模式',
    themeLight: '浅色模式',
    switchLang: '切换语言',
  }
};

export const AVAILABLE_LANGUAGES = [
  { code: 'en', name: 'English', flag: 'EN', label: 'EN' },
  { code: 'bn', name: 'বাংলা (Bengali)', flag: 'BN', label: 'BN' },
  { code: 'es', name: 'Español', flag: 'ES', label: 'ES' },
  { code: 'de', name: 'Deutsch', flag: 'DE', label: 'DE' },
  { code: 'fr', name: 'Français', flag: 'FR', label: 'FR' },
  { code: 'ru', name: 'Русский', flag: 'RU', label: 'RU' },
  { code: 'zh', name: '中文 (Chinese)', flag: 'ZH', label: 'ZH' },
];

export const TYPEWRITER_WORDS = {
  en: ['everyone!', 'game developers!', 'software creators!', 'security pros!', 'enterprises!'],
  bn: ['সবার জন্য!', 'গেম ডেভেলপারদের!', 'সফটওয়্যার নির্মাতাদের!', 'নিরাপত্তা বিশেষজ্ঞদের!', 'এন্টারপ্রাইজের!'],
  es: ['¡todos!', '¡desarrolladores de juegos!', '¡creadores de software!', '¡expertos de seguridad!', '¡empresas!'],
  de: ['jeden!', 'Spieleentwickler!', 'Software-Schöpfer!', 'Sicherheitsexperten!', 'Unternehmen!'],
  fr: ['tous!', 'développeurs de jeux!', 'créateurs de logiciels!', 'experts en sécurité!', 'entreprises!'],
  ru: ['всех!', 'разработчиков игр!', 'создателей ПО!', 'экспертов безопасности!', 'корпораций!'],
  zh: ['每个人！', '游戏开发者！', '软件创作者！', '网络安全专家！', '企业用户！']
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [currentLang, setCurrentLang] = useState(() => {
    return localStorage.getItem('habit_lang') || 'en';
  });

  const setLanguage = (langCode) => {
    if (translations[langCode]) {
      setCurrentLang(langCode);
      localStorage.setItem('habit_lang', langCode);
    }
  };

  const t = (key) => {
    const dict = translations[currentLang] || translations.en;
    return dict[key] || translations.en[key] || key;
  };

  const currentLanguageObj = AVAILABLE_LANGUAGES.find(l => l.code === currentLang) || AVAILABLE_LANGUAGES[0];

  return (
    <LanguageContext.Provider value={{
      currentLang,
      language: currentLang,
      setLanguage,
      t,
      languages: AVAILABLE_LANGUAGES,
      currentLanguageObj,
      typewriterWords: TYPEWRITER_WORDS[currentLang] || TYPEWRITER_WORDS.en
    }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) {
    return {
      currentLang: 'en',
      language: 'en',
      setLanguage: () => {},
      t: (key) => key,
      languages: AVAILABLE_LANGUAGES,
      currentLanguageObj: AVAILABLE_LANGUAGES[0],
      typewriterWords: TYPEWRITER_WORDS.en
    };
  }
  return ctx;
}
